Repository share-dev24/GoodEDay, pull requests merged in 2024-05, with the labels that each got.

#8 docs: "tailwindCSS 설정 파일 수정, global style reset 코드 추가"
  src/index.css
  tailwind.config.js
Labels: set

#9 style: "MapLink 컴포넌트"
  src/components/common/MapLink.tsx
  src/components/common/UserProfileSection.tsx
Labels: enhancement

#10 style: "createCard page의 Container, Title, SpanText, BasicButton UI 구현과 login page의 LoginButton UI 구현"
  src/components/common/createCard/BasicButton.tsx
  src/components/common/createCard/FormContainer.tsx
  src/components/common/createCard/FormSpanText.tsx
  src/components/common/createCard/FormTitle.tsx
  src/components/common/login/LoginButton.tsx
  tailwind.config.js
Labels: bug, documentation, enhancement

#11 style: "ProfileBasicButton 컴포넌트 UI 구현"
  src/Router.tsx
  src/components/common/profile/ProfileBasicButton.tsx
Labels: enhancement

#13 style: "공통 컴포넌트 제작( 기본 레이아웃, post 카드와 레이아웃, theme 카드와 레이아웃 등)"
  src/assets/images/a.jpg
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/common/Container.tsx
  src/components/common/FilteringButton.tsx
  src/components/common/Logo.tsx
  src/components/common/MainTitle.tsx
  src/components/common/SubTitle.tsx
  src/components/common/ThemeBadge.tsx
  src/components/common/ThemeCard.tsx
  src/components/common/ThemeCardsGrid.tsx
  src/components/posts/HeartIcon.tsx
  src/components/posts/PopupLayout.tsx
  src/components/posts/PostCard.tsx
  src/components/posts/PostCardsGrid.tsx
  src/components/posts/ShowMoreButton.tsx
  src/modules/ThemeNameCompiling.tsx
Labels: enhancement, set

#14 docs: "static data 작성, 타입 설정"
  src/stores/static.ts
  src/types/staticType.ts
Labels: documentation

#17 feat: "굳이데이 랜덤카드 생성 컴포넌트 로직 구현, 카카오 api 연결"
  .gitignore
  package.json
  src/components/common/BasicButton.tsx
  src/components/common/FormContainer.tsx
  src/components/common/FormSpanText.tsx
  src/components/common/FormTitle.tsx
  src/components/common/createCard/FormContainer.tsx
  src/components/createCard/CreateForm.tsx
  src/components/createCard/CreateFormTitle.tsx
  src/components/createCard/KakaoPlace.tsx
  src/components/createCard/form-elements/CreateFormBtn.tsx
  src/components/createCard/form-elements/CreateFormCheckbox.tsx
  src/components/createCard/form-elements/CreateFormInput.tsx
  src/components/createCard/form-elements/CreateFormSelect.tsx
  src/components/login/LoginButton.tsx
  src/components/profile/ProfileBasicButton.tsx
  src/modules/map/map.ts
  src/routes/CompletedCard.tsx
  src/routes/CreateCard.tsx
  yarn.lock
Labels: documentation, enhancement

#18 feat: "footer 컴포넌트 생성 및 UI 구현, 정적 데이터 파일 수정, interface 파일 생성"
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/common/FormContainer.tsx
  src/components/createCard/CreateForm.tsx
  src/components/createCard/KakaoPlace.tsx
  src/components/createCard/form-elements/CreateFormBtn.tsx
  src/components/createCard/form-elements/CreateFormCheckbox.tsx
  src/components/createCard/form-elements/CreateFormInput.tsx
  src/components/createCard/form-elements/CreateFormSelect.tsx
  src/modules/map/map.ts
  src/stores/static.ts
  src/types/createCardType.ts
  src/types/staticType.ts
  tailwind.config.js
Labels: documentation, enhancement

#22 feat: "굳이데이 랜덤카드 생성 컴포넌트 수정, 완성된 굳이데이 랜덤카드 컴포넌트 UI 및 로직 구현, 카카오 map api 연결"
  .gitignore
  index.html
  package.json
  src/components/completedCard/CompletedCardBtn.tsx
  src/components/completedCard/KakaoMap.tsx
  src/components/createCard/CreateForm.tsx
  src/components/createCard/CreateFormTitle.tsx
  src/components/createCard/KakaoPlace.tsx
  src/components/createCard/form-elements/CreateFormBtn.tsx
  src/modules/map/map.ts
  src/routes/CompletedCard.tsx
  src/routes/CreateCard.tsx
  src/types/createCardType.ts
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement, set

#24 feat: "NotFount 컴포넌트 UI 구현"
  src/screens/NotFound.tsx
Labels: enhancement

#26 fix: "div의 background 이미지 -> img 태그로 변경"
  src/components/common/ThemeBadge.tsx
  src/components/common/ThemeCard.tsx
  src/routes/Main.tsx
Labels: style

#25 feat: "좋아요 기능 구현"
  src/Router.tsx
  src/assets/images/user.svg
  src/components/login/LoginButton.tsx
  src/components/posts/HeartIcon.tsx
  src/components/posts/PopupLayout.tsx
  src/components/posts/PostCard.tsx
  src/components/posts/PostCardsSection.tsx
  src/components/posts/ShowMoreButton.tsx
  src/components/profile/LikeCardsSection.tsx
  src/fetch/get.ts
  src/fetch/update.ts
  src/modules/ScrollToTop.tsx
  src/modules/TimeCompiler.tsx
  src/routes/Login.tsx
  src/routes/Main.tsx
  src/routes/PostDetail.tsx
  src/routes/Posts.tsx
  src/routes/Profile.tsx
  src/stores/store.ts
  src/types/postCardsType.tsx
  src/types/staticType.ts
Labels: documentation, enhancement
